blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: mailto:dave@pattens.org
    about: Please report security vulnerabilities via email
  - name: Questions & Discussions
    url: https://github.com/starman69/mcp-sanitizer/discussions
    about: Ask questions and discuss ideas